[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
projeto_kaonashi = "4ybufDXMBSQpQ6kxGqEud9afLC9ayoN925Fk6SkAJxx7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo run -p zk-client"
