use crate::models::PendingEncryptedVote;

use ark_bn254::{Bn254, Fq, Fq2, Fr, G1Affine, G2Affine};
use ark_ff::{BigInteger, PrimeField};
use ark_groth16::{prepare_verifying_key, Groth16, ProvingKey};
use ark_relations::{
    lc,
    r1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError, Variable},
};
use ark_serialize::CanonicalDeserialize;
use ark_std::test_rng;

use std::{
    fs,
    time::{Duration, Instant},
};

// ============================================================================
// Fixed Groth16 configuration
// ============================================================================

/// The current Groth16 setup was generated specifically for a
/// BatchCircuit containing exactly 10 private vote commitments.
pub const GROTH16_BATCH_SIZE: usize = 10;

/// Fixed proving key generated by:
///
/// cargo run --bin generate_groth16_setup
///
/// IMPORTANT:
/// Do not regenerate this file unless the corresponding verifying
/// key in the Solana smart contract is regenerated at the same time.
const PROVING_KEY_PATH: &str = "data/groth16/batch10_proving_key.bin";

// ============================================================================
// Proof result
// ============================================================================

/// Result produced by the Groth16 batch prover.
///
/// It contains:
/// - the Arkworks proof;
/// - the serialized 256-byte proof expected by groth16-solana;
/// - the two public inputs;
/// - timing information.
pub struct BatchProofResult {
    pub proof: ark_groth16::Proof<Bn254>,

    /// Serialized Groth16 proof:
    ///
    /// -A = 64 bytes
    ///  B = 128 bytes
    ///  C = 64 bytes
    ///
    /// Total = 256 bytes.
    pub proof_bytes: [u8; 256],

    pub batch_commitment: Fr,
    pub batch_size: Fr,

    /// Public inputs serialized in big-endian representation.
    ///
    /// [0] = batch_commitment
    /// [1] = batch_size
    pub public_inputs_bytes: [[u8; 32]; 2],

    /// Time required to load and deserialize the proving key.
    ///
    /// This is NOT Groth16 setup time.
    pub proving_key_load_time: Duration,

    pub proof_generation_time: Duration,
    pub local_verification_time: Duration,
}

// ============================================================================
// Batch circuit
// ============================================================================

/// Minimal Kaonashi Groth16 batch circuit.
///
/// PRIVATE INPUTS:
///     one field-element commitment for each encrypted vote
///
/// PUBLIC INPUTS:
///     batch_commitment
///     batch_size
///
/// PROVES:
///
///     vote_commitment_0
///       + vote_commitment_1
///       + ...
///       + vote_commitment_n
///       == batch_commitment
///
/// AND:
///
///     number of commitments == batch_size
///
/// IMPORTANT:
///
/// This circuit does NOT yet prove:
///
/// - the existing SHA-based Merkle root;
/// - the homomorphic ElGamal batch tally.
///
/// Those bindings will be strengthened later.
#[derive(Clone)]
pub struct BatchCircuit {
    pub vote_commitments: Vec<Option<Fr>>,
    pub batch_commitment: Option<Fr>,
    pub batch_size: Option<Fr>,
}

impl ConstraintSynthesizer<Fr> for BatchCircuit {
    fn generate_constraints(self, cs: ConstraintSystemRef<Fr>) -> Result<(), SynthesisError> {
        // ---------------------------------------------------------
        // Public input #1: batch commitment
        // ---------------------------------------------------------

        let batch_commitment_var = cs.new_input_variable(|| {
            self.batch_commitment
                .ok_or(SynthesisError::AssignmentMissing)
        })?;

        // ---------------------------------------------------------
        // Public input #2: batch size
        // ---------------------------------------------------------

        let batch_size_var =
            cs.new_input_variable(|| self.batch_size.ok_or(SynthesisError::AssignmentMissing))?;

        // ---------------------------------------------------------
        // Constraint #1
        //
        // sum(private vote commitments)
        //     == public batch commitment
        // ---------------------------------------------------------

        let mut commitment_sum = lc!();

        for commitment in &self.vote_commitments {
            let commitment_var =
                cs.new_witness_variable(|| commitment.ok_or(SynthesisError::AssignmentMissing))?;

            commitment_sum = commitment_sum + commitment_var;
        }

        cs.enforce_constraint(
            commitment_sum,
            lc!() + Variable::One,
            lc!() + batch_commitment_var,
        )?;

        // ---------------------------------------------------------
        // Constraint #2
        //
        // public batch_size must equal the circuit shape.
        // ---------------------------------------------------------

        let expected_batch_size = Fr::from(self.vote_commitments.len() as u64);

        cs.enforce_constraint(
            lc!() + (expected_batch_size, Variable::One),
            lc!() + Variable::One,
            lc!() + batch_size_var,
        )?;

        Ok(())
    }
}

// ============================================================================
// Serialization helpers
// ============================================================================

/// Convert a BN254 base-field value into 32-byte big endian.
fn fq_to_be(value: &Fq) -> [u8; 32] {
    let bytes = value.into_bigint().to_bytes_be();

    let mut out = [0u8; 32];

    out[32 - bytes.len()..].copy_from_slice(&bytes);

    out
}

/// Convert a BN254 scalar-field value into 32-byte big endian.
///
/// groth16-solana expects public inputs in this representation.
fn fr_to_be(value: &Fr) -> [u8; 32] {
    let bytes = value.into_bigint().to_bytes_be();

    let mut out = [0u8; 32];

    out[32 - bytes.len()..].copy_from_slice(&bytes);

    out
}

/// Serialize a G1 point as:
///
/// x || y
///
/// 32 + 32 = 64 bytes.
fn g1_to_bytes(point: &G1Affine) -> [u8; 64] {
    let mut out = [0u8; 64];

    out[..32].copy_from_slice(&fq_to_be(&point.x));

    out[32..].copy_from_slice(&fq_to_be(&point.y));

    out
}

/// Serialize Fq2 using the ordering expected by groth16-solana:
///
/// c1 || c0
fn fq2_to_bytes(value: &Fq2) -> [u8; 64] {
    let mut out = [0u8; 64];

    out[..32].copy_from_slice(&fq_to_be(&value.c1));

    out[32..].copy_from_slice(&fq_to_be(&value.c0));

    out
}

/// Serialize a G2 point.
///
/// x = 64 bytes
/// y = 64 bytes
///
/// Total = 128 bytes.
fn g2_to_bytes(point: &G2Affine) -> [u8; 128] {
    let mut out = [0u8; 128];

    out[..64].copy_from_slice(&fq2_to_bytes(&point.x));

    out[64..].copy_from_slice(&fq2_to_bytes(&point.y));

    out
}

/// Convert an Arkworks Groth16 proof into the exact representation
/// expected by groth16-solana.
///
/// groth16-solana's pairing equation expects -A.
///
/// Layout:
///
/// -A = bytes 0..64
///  B = bytes 64..192
///  C = bytes 192..256
fn serialize_proof(proof: &ark_groth16::Proof<Bn254>) -> [u8; 256] {
    let proof_a_neg = -proof.a;

    let proof_a = g1_to_bytes(&proof_a_neg);

    let proof_b = g2_to_bytes(&proof.b);

    let proof_c = g1_to_bytes(&proof.c);

    let mut out = [0u8; 256];

    out[0..64].copy_from_slice(&proof_a);

    out[64..192].copy_from_slice(&proof_b);

    out[192..256].copy_from_slice(&proof_c);

    out
}

// ============================================================================
// Kaonashi vote -> field element
// ============================================================================

/// Convert one real Kaonashi encrypted vote into a BN254 scalar.
///
/// The resulting scalar is used as the private witness value
/// for the current BatchCircuit.
///
/// The conversion includes:
///
/// - wallet id
/// - voter public key
/// - decade id
/// - encrypted vote hash
/// - all encrypted ciphertext bytes
///
/// IMPORTANT:
///
/// This is currently a deterministic field mapping, not the existing
/// Merkle leaf hash.
fn encrypted_vote_to_field(vote: &PendingEncryptedVote) -> Fr {
    let mut bytes = Vec::new();

    bytes.extend_from_slice(vote.wallet_id.as_bytes());

    bytes.extend_from_slice(vote.public_key.as_bytes());

    bytes.push(vote.decade_id);

    bytes.extend_from_slice(vote.encrypted_vote_hash.as_bytes());

    for ciphertext in &vote.encrypted_vote {
        bytes.extend_from_slice(ciphertext);
    }

    Fr::from_le_bytes_mod_order(&bytes)
}

/// Sum all private vote commitments into the public batch commitment.
fn calculate_batch_commitment(commitments: &[Fr]) -> Fr {
    commitments
        .iter()
        .copied()
        .fold(Fr::from(0u64), |acc, value| acc + value)
}

// ============================================================================
// Fixed proving key
// ============================================================================

/// Loads the proving key generated once by:
///
/// cargo run --bin generate_groth16_setup
///
/// The corresponding verifying key is stored in the Solana program.
///
/// This function does NOT perform trusted setup.
fn load_proving_key() -> Result<ProvingKey<Bn254>, String> {
    let bytes = fs::read(PROVING_KEY_PATH).map_err(|error| {
        format!(
            "Failed to read Groth16 proving key from {}: {}",
            PROVING_KEY_PATH, error
        )
    })?;

    ProvingKey::<Bn254>::deserialize_compressed(bytes.as_slice())
        .map_err(|error| format!("Failed to deserialize Groth16 proving key: {}", error))
}

// ============================================================================
// Batch proof generation
// ============================================================================

/// Generate and locally verify a Groth16 proof for a real Kaonashi batch.
///
/// The current setup supports exactly 10 votes.
pub fn generate_batch_proof(votes: &[PendingEncryptedVote]) -> Result<BatchProofResult, String> {
    // ---------------------------------------------------------
    // Basic validation
    // ---------------------------------------------------------

    if votes.is_empty() {
        return Err("Cannot generate Groth16 proof for empty batch".to_string());
    }

    if votes.len() != GROTH16_BATCH_SIZE {
        return Err(format!(
            "Groth16 BatchCircuit currently supports exactly {} votes, received {}",
            GROTH16_BATCH_SIZE,
            votes.len()
        ));
    }

    println!(
        "Generating Groth16 proof for Kaonashi batch of {} votes",
        votes.len()
    );

    // ---------------------------------------------------------
    // Build private witness values
    // ---------------------------------------------------------

    let vote_commitments = votes
        .iter()
        .map(encrypted_vote_to_field)
        .collect::<Vec<Fr>>();

    let batch_commitment = calculate_batch_commitment(&vote_commitments);

    let batch_size = Fr::from(votes.len() as u64);

    // ---------------------------------------------------------
    // Load fixed proving key
    // ---------------------------------------------------------

    let key_load_start = Instant::now();

    let proving_key = load_proving_key()?;

    let proving_key_load_time = key_load_start.elapsed();

    println!("Groth16 proving key load time: {:?}", proving_key_load_time);

    // Local verification uses the verifying key embedded
    // in the fixed proving key.
    let prepared_verifying_key = prepare_verifying_key(&proving_key.vk);

    // ---------------------------------------------------------
    // Build circuit witness
    // ---------------------------------------------------------

    let proof_circuit = BatchCircuit {
        vote_commitments: vote_commitments.iter().copied().map(Some).collect(),

        batch_commitment: Some(batch_commitment),

        batch_size: Some(batch_size),
    };

    // ---------------------------------------------------------
    // Generate proof
    // ---------------------------------------------------------

    let mut rng = test_rng();

    let proof_start = Instant::now();

    let proof =
        Groth16::<Bn254>::create_random_proof_with_reduction(proof_circuit, &proving_key, &mut rng)
            .map_err(|error| format!("Groth16 batch proof generation failed: {}", error))?;

    let proof_generation_time = proof_start.elapsed();

    println!("Groth16 proof generation time: {:?}", proof_generation_time);

    // ---------------------------------------------------------
    // Local verification
    // ---------------------------------------------------------

    let public_inputs = [batch_commitment, batch_size];

    let verification_start = Instant::now();

    let valid = Groth16::<Bn254>::verify_proof(&prepared_verifying_key, &proof, &public_inputs)
        .map_err(|error| format!("Groth16 local verification failed: {}", error))?;

    let local_verification_time = verification_start.elapsed();

    println!(
        "Groth16 local verification time: {:?}",
        local_verification_time
    );

    if !valid {
        return Err("Generated Groth16 batch proof is invalid".to_string());
    }

    println!("Kaonashi Groth16 batch proof valid: true");

    // ---------------------------------------------------------
    // Serialize for Solana
    // ---------------------------------------------------------

    let proof_bytes = serialize_proof(&proof);

    let public_inputs_bytes = [fr_to_be(&batch_commitment), fr_to_be(&batch_size)];

    println!("Groth16 serialized proof size: {} bytes", proof_bytes.len());

    println!(
        "Groth16 serialized public inputs: {} bytes",
        public_inputs_bytes.len() * 32
    );

    // ---------------------------------------------------------
    // Result
    // ---------------------------------------------------------

    Ok(BatchProofResult {
        proof,
        proof_bytes,

        batch_commitment,
        batch_size,

        public_inputs_bytes,

        proving_key_load_time,
        proof_generation_time,
        local_verification_time,
    })
}
